#!/usr/bin/env python3
"""Open (or refresh) a sync PR on cailum-blue/agentic-sdlc that makes it match this repo.

    sync-to-work-repo.py <source-dir> <work-checkout-dir>

<source-dir> is a checkout of mschabow/agentic-sdlc with scripts/work-mirror-overlay.py already
applied. <work-checkout-dir> is a checkout of cailum-blue/agentic-sdlc main. Files under .git/ and
.github/ are left out on both sides (pushing workflow files needs a wider token).

cailum-blue requires signed commits on every branch and a reviewed PR into main, so the commit is
made with the GraphQL createCommitOnBranch mutation (GitHub signs it) on the branch mirror/sync,
reset to main first, and one PR from that branch is opened or updated. Needs GH_TOKEN with Contents
and Pull requests read/write on cailum-blue/agentic-sdlc.
"""
import base64
import filecmp
import json
import os
import pathlib
import sys
import urllib.request

REPO = "cailum-blue/agentic-sdlc"
BRANCH = "mirror/sync"
SKIP_TOP = {".git", ".github"}


def api(method, path, body=None):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        method=method,
        data=None if body is None else json.dumps(body).encode(),
        headers={
            "Authorization": f"Bearer {os.environ['GH_TOKEN']}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
    )
    try:
        with urllib.request.urlopen(req) as r:
            raw = r.read()
            return r.status, (json.loads(raw) if raw else None)
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read() or b"null")


def graphql(query, variables):
    status, out = api("POST", "/graphql", {"query": query, "variables": variables})
    if status != 200 or out.get("errors"):
        sys.exit(f"graphql failed ({status}): {out}")
    return out["data"]


def files(root: pathlib.Path):
    out = {}
    for p in root.rglob("*"):
        rel = p.relative_to(root)
        if rel.parts[0] in SKIP_TOP or not p.is_file():
            continue
        out[rel.as_posix()] = p
    return out


def main() -> int:
    src, dst = (pathlib.Path(a).resolve() for a in sys.argv[1:3])
    source_sha = os.environ.get("SOURCE_SHA", "")[:7] or "local"
    a, b = files(src), files(dst)
    additions = [
        {"path": k, "contents": base64.b64encode(v.read_bytes()).decode()}
        for k, v in sorted(a.items())
        if k not in b or not filecmp.cmp(v, b[k], shallow=False)
    ]
    deletions = [{"path": k} for k in sorted(b) if k not in a]
    if not additions and not deletions:
        print("work repo already matches; nothing to do")
        return 0
    print(f"{len(additions)} changed or new, {len(deletions)} removed")

    status, main_ref = api("GET", f"/repos/{REPO}/git/ref/heads/main")
    if status != 200:
        sys.exit(f"cannot read main: {status} {main_ref}")
    main_sha = main_ref["object"]["sha"]

    # the sync branch always starts from main, so the PR holds exactly one commit
    status, _ = api("GET", f"/repos/{REPO}/git/ref/heads/{BRANCH}")
    if status == 200:
        status, out = api("PATCH", f"/repos/{REPO}/git/refs/heads/{BRANCH}", {"sha": main_sha, "force": True})
    else:
        status, out = api("POST", f"/repos/{REPO}/git/refs", {"ref": f"refs/heads/{BRANCH}", "sha": main_sha})
    if status not in (200, 201):
        sys.exit(f"cannot set {BRANCH}: {status} {out}")

    headline = f"Sync from mschabow/agentic-sdlc@{source_sha}"
    data = graphql(
        """mutation($input: CreateCommitOnBranchInput!) {
             createCommitOnBranch(input: $input) { commit { oid url } } }""",
        {
            "input": {
                "branch": {"repositoryNameWithOwner": REPO, "branchName": BRANCH},
                "expectedHeadOid": main_sha,
                "message": {
                    "headline": headline,
                    "body": "Files now match mschabow/agentic-sdlc plus the work-repo overlay "
                    "(install from cailum-blue/agentic-sdlc). Generated by scripts/sync-to-work-repo.py.",
                },
                "fileChanges": {"additions": additions, "deletions": deletions},
            }
        },
    )
    commit = data["createCommitOnBranch"]["commit"]
    print(f"signed commit {commit['oid'][:7]} {commit['url']}")

    changed = "\n".join(f"- `{x['path']}`" for x in additions[:40])
    removed = "\n".join(f"- `{x['path']}`" for x in deletions[:40])
    body = (
        f"Brings `cailum-blue/agentic-sdlc` in line with `mschabow/agentic-sdlc@{source_sha}`, "
        "keeping this repo's install path (`/plugin marketplace add cailum-blue/agentic-sdlc`, "
        "marketplace `sw-development-process`).\n\n"
        "Change the personal repo, not this one: the next sync replaces this branch.\n\n"
        f"**Changed or new ({len(additions)})**\n{changed or '- none'}\n\n"
        f"**Removed ({len(deletions)})**\n{removed or '- none'}\n\n"
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n"
    )
    status, prs = api("GET", f"/repos/{REPO}/pulls?head=cailum-blue:{BRANCH}&state=open")
    if prs:
        num = prs[0]["number"]
        api("PATCH", f"/repos/{REPO}/pulls/{num}", {"title": headline, "body": body})
        print(f"updated PR https://github.com/{REPO}/pull/{num}")
    else:
        status, pr = api("POST", f"/repos/{REPO}/pulls", {"title": headline, "head": BRANCH, "base": "main", "body": body})
        if status != 201:
            sys.exit(f"cannot open PR: {status} {pr}")
        print(f"opened PR {pr['html_url']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
